name: bendaron
favicon: null
layout_spectrum: 0.258
typography_spectrum: 0.30598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdce1'
    - '#e0a200'
    - '#6f655a'
    - '#1a292e'
    - '#aea199'
  brandStrength: 0.625
  lightness: 0.8347402077633888
  saturation: 0.3912080032750964
  rhythmicContrast: 0.6528146385680884
purpose: []
